// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.45.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in CyberGuard Academy user's profile (full name, bio, avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, avatar_url, bio, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.45.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_my_profile_default = defineTool2({
  name: "update_my_profile",
  title: "Update my profile",
  description: "Update the signed-in user's full name and/or bio on their CyberGuard Academy profile.",
  inputSchema: {
    full_name: z.string().trim().min(1).max(120).optional().describe("New display name"),
    bio: z.string().trim().max(1e3).optional().describe("Short bio / about text")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ full_name, bio }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (full_name !== void 0) patch.full_name = full_name;
    if (bio !== void 0) patch.bio = bio;
    if (Object.keys(patch).length === 0) {
      return { content: [{ type: "text", text: "No fields provided to update." }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("profiles").update(patch).eq("id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Profile updated: ${JSON.stringify(data)}` }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-my-roles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.45.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_roles_default = defineTool3({
  name: "get_my_roles",
  title: "Get my roles",
  description: "Return the signed-in user's roles (admin, instructor, or student) in CyberGuard Academy.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("user_roles").select("role, created_at").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const roles = (data ?? []).map((r) => r.role);
    return {
      content: [{ type: "text", text: `Roles: ${roles.join(", ") || "(none)"}` }],
      structuredContent: { roles }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var COURSES = [
  {
    id: "1",
    title: "Cybersecurity Fundamentals",
    level: "Beginner",
    modules: 8,
    description: "Core concepts and principles of cybersecurity."
  },
  {
    id: "2",
    title: "Network Security",
    level: "Intermediate",
    modules: 12,
    description: "Protect computer networks from intrusion and attacks."
  },
  {
    id: "3",
    title: "Ethical Hacking",
    level: "Advanced",
    modules: 15,
    description: "Techniques used by hackers to identify vulnerabilities."
  },
  {
    id: "4",
    title: "Web Application Security",
    level: "Intermediate",
    modules: 10,
    description: "Secure web applications from common attacks (OWASP Top 10)."
  },
  {
    id: "5",
    title: "Database Security",
    level: "Intermediate",
    modules: 9,
    description: "Protect sensitive data and secure database systems."
  },
  {
    id: "6",
    title: "Threat Intelligence",
    level: "Advanced",
    modules: 14,
    description: "Identify and respond to security threats effectively."
  }
];
var list_courses_default = defineTool4({
  name: "list_courses",
  title: "List courses",
  description: "Return the full catalog of CyberGuard Academy cybersecurity courses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(COURSES, null, 2) }],
    structuredContent: { courses: COURSES }
  })
});

// src/lib/mcp/index.ts
var projectRef = "znorthyqczdcdfkerwmq";
var mcp_default = defineMcp({
  name: "cyberguard-academy-mcp",
  title: "CyberGuard Academy",
  version: "0.1.0",
  instructions: "Tools for CyberGuard Academy, a cybersecurity learning platform. Use `list_courses` to browse the catalog, `get_my_profile` / `update_my_profile` for the signed-in user's profile, and `get_my_roles` to check the user's role.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, get_my_profile_default, update_my_profile_default, get_my_roles_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
